repos:
  - repo: local
    hooks:
      - id: add-spdx-header
        name: Add SPDX Header
        entry: python3 scripts/add_spdx_headers.py
        language: system
        types: [python, rust, javascript, shell, dockerfile]
        files: \.(py|rs|js|ts|sh|bash|zsh)$|Dockerfile
