[package]
name = "runegate"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
dotenvy = "0.15.7"
jsonwebtoken = "9.3.1"
lettre = { version = "0.11.16", features = ["smtp-transport", "tokio1", "builder", "tokio1-native-tls"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
toml = "0.8.22"
uuid = { version = "1.16.0", features = ["v4"] }
